<?php
return ['senderExport' => [
2 => [
'id' => '2',
'code' => 'an-danh',
'name' => 'Ẩn Danh',
'avatar' => '',
],
3 => [
'id' => '3',
'code' => 'bang-thong',
'name' => 'Bàng Thống',
'avatar' => '',
],
4 => [
'id' => '4',
'code' => 'bao-ngoc',
'name' => 'Bảo Ngọc',
'avatar' => '',
],
5 => [
'id' => '5',
'code' => 'bong-tron',
'name' => 'Bóng Tròn',
'avatar' => '',
],
6 => [
'id' => '6',
'code' => 'chieu-suong',
'name' => 'Chiểu Sương',
'avatar' => '',
],
7 => [
'id' => '7',
'code' => 'doanh-doanh',
'name' => 'Doanh Doanh',
'avatar' => '',
],
8 => [
'id' => '8',
'code' => 'duong-anh',
'name' => 'Dương Anh',
'avatar' => '',
],
9 => [
'id' => '9',
'code' => 'ha-di',
'name' => 'Hà Di',
'avatar' => '',
],
10 => [
'id' => '10',
'code' => 'hoang-anh',
'name' => 'Hoàng Anh',
'avatar' => '',
],
11 => [
'id' => '11',
'code' => 'hoang-ngoc',
'name' => 'Hoàng Ngọc',
'avatar' => '',
],
12 => [
'id' => '12',
'code' => 'hoang-tai',
'name' => 'Hoàng Tài',
'avatar' => '',
],
13 => [
'id' => '13',
'code' => 'hong-ngoc',
'name' => 'Hồng Ngọc',
'avatar' => '',
],
14 => [
'id' => '14',
'code' => 'hu-van',
'name' => 'Hư Vân',
'avatar' => '',
],
15 => [
'id' => '15',
'code' => 'hung-yen',
'name' => 'hung yen',
'avatar' => '',
],
16 => [
'id' => '16',
'code' => 'hung-yen-thanh-vien-cong-dong',
'name' => 'hung yen- Thành viên cộng đồng',
'avatar' => '',
],
17 => [
'id' => '17',
'code' => 'huy-hoang',
'name' => 'Huy Hoàng',
'avatar' => '',
],
18 => [
'id' => '18',
'code' => 'loc-son',
'name' => 'Lộc Sơn',
'avatar' => '',
],
19 => [
'id' => '19',
'code' => 'minh-khang',
'name' => 'MINH KHANG',
'avatar' => '',
],
20 => [
'id' => '20',
'code' => 'minh-minh',
'name' => 'Minh Minh',
'avatar' => '',
],
21 => [
'id' => '21',
'code' => 'minh-nhat',
'name' => 'Minh Nhật',
'avatar' => '',
],
22 => [
'id' => '22',
'code' => 'minh-tam',
'name' => 'Minh Tâm',
'avatar' => '',
],
23 => [
'id' => '23',
'code' => 'minh-vu',
'name' => 'Minh Vũ',
'avatar' => '',
],
24 => [
'id' => '24',
'code' => 'nam-phong',
'name' => 'Nam Phong',
'avatar' => '',
],
25 => [
'id' => '25',
'code' => 'ngoc-anh',
'name' => 'NGỌC ANH',
'avatar' => '',
],
26 => [
'id' => '26',
'code' => 'ngoc-tan',
'name' => 'NGỌC TÂN',
'avatar' => '',
],
27 => [
'id' => '27',
'code' => 'nguyen-an',
'name' => 'Nguyên An',
'avatar' => '',
],
28 => [
'id' => '28',
'code' => 'nguyen-vu',
'name' => 'NGUYÊN VŨ',
'avatar' => '',
],
29 => [
'id' => '29',
'code' => 'phong-lan',
'name' => 'Phong Lan',
'avatar' => '',
],
30 => [
'id' => '30',
'code' => 'phong-van',
'name' => 'Phong Vân',
'avatar' => '',
],
31 => [
'id' => '31',
'code' => 'phuong-anh',
'name' => 'Phương Anh',
'avatar' => '',
],
32 => [
'id' => '32',
'code' => 'quoc-toan',
'name' => 'QUỐC TOÀN',
'avatar' => '',
],
33 => [
'id' => '33',
'code' => 'soi',
'name' => 'Soi',
'avatar' => '',
],
34 => [
'id' => '34',
'code' => 'thanh-diep',
'name' => 'Thanh Diệp',
'avatar' => '',
],
35 => [
'id' => '35',
'code' => 'thanh-nhat',
'name' => 'Thành Nhật',
'avatar' => '',
],
36 => [
'id' => '36',
'code' => 'thanh-thanh',
'name' => 'Thanh Thanh',
'avatar' => '',
],
37 => [
'id' => '37',
'code' => 'thuy-tien',
'name' => 'Thủy Tiên',
'avatar' => '',
],
38 => [
'id' => '38',
'code' => 'tieu-phong',
'name' => 'Tiểu Phong',
'avatar' => '',
],
39 => [
'id' => '39',
'code' => 'trang-anh',
'name' => 'Trang Anh',
'avatar' => '',
],
40 => [
'id' => '40',
'code' => 'vo-danh',
'name' => 'Vô Danh',
'avatar' => '',
],
41 => [
'id' => '41',
'code' => 'yen-van',
'name' => 'Yến Vân',
'avatar' => '',
],
42 => [
'id' => '42',
'code' => 'ygeteb',
'name' => 'Ygeteb',
'avatar' => '',
],
] ];