<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'yii\\imperavi\\' => array($vendorDir . '/asofter/yii2-imperavi-redactor'),
    'Props\\' => array($vendorDir . '/mrclay/props-dic/src', $vendorDir . '/mrclay/props-dic/test'),
    'Pimple' => array($vendorDir . '/pimple/pimple/src'),
    'JShrink' => array($vendorDir . '/tedivm/jshrink/src'),
    'JSMin\\' => array($vendorDir . '/mrclay/jsmin-php/src'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
    'Diff' => array($vendorDir . '/phpspec/php-diff/lib'),
    'Behat\\Gherkin' => array($vendorDir . '/behat/gherkin/src'),
);
