<?php
return [
    'request'=>[
        'class'=>'common\components\HttpRequest',
    ],
    'user' => [
        'class'=>'yii\web\User',
        'identityClass' => 'common\models\UserBase',
        'enableAutoLogin' => true,
        'loginUrl'=>'/default/login',
    ],
    'gearman' => [
        'class' => 'shakura\yii2\gearman\GearmanComponent',
        'servers' => [
            ['host' => '127.0.0.1', 'port' => 4730],
        ],
        'user' => 'developer',
        'jobs' => [
            'sendSms' => [
                'class' => 'common\components\script\jobs\SendSms'
            ],
            'Gamification' => [
                'class' => 'common\components\Gamification'
            ],
        ]
    ],
    'telco'=>[
//        'class'=>'vega\telco\vinaphone\Vinaphone',
        'class'=>'vega\telco\viettel\Viettel',
        'recognizers'=>[
            'headerRecognizer'=>[
                'class'=>'vega\telco\vinaphone\recognizing\HeaderRecognizer',
                'mSISDNHeaders'=>[
                    'HTTP_MSISDN',
                    'HTTP_X_WAP_MSISDN',
                    'X_WAP_MSISDN',
                    'X-WAP-MSISDN',
                    'X-Wap-MSISDN',
                    'MSISDN',
                    'msisdn',
                ],
            ]
        ],
        'chargers'=>[
            'package'=>[
                'class'=>'vega\telco\vinaphone\charging\PackageCharger',
                'baseUrl'=>'http://10.1.10.86:8080/billing/billing',
                'chargerName'=>'VCLIP',
                'username'=>'vclip',
                'password'=>'vclip#vega@2012',
                'behaviors'=>[
                    'logMysqlDB'=>[
                        'class'=>'common\components\script\behaviors\charging\LogMysqlDBChargingBehavior'
                    ],
                    'logFile'=>[
                        'class'=>'common\components\script\behaviors\charging\LogFileChargingBehavior'
                    ],
                    'logMongoDB'=>[
                        'class'=>'common\components\script\behaviors\charging\LogMongoDBChargingBehavior'
                    ],
                ]
            ],
            'test'=>[
                'class'=>'common\components\test\Charger',
                'baseUrl'=>'http://10.1.10.86:8080/billing/billing',
                'chargerName'=>'VCLIP',
                'username'=>'vclip',
                'password'=>'vclip#vega@2012',
                'behaviors'=>[
                    'logMysqlDB'=>[
                        'class'=>'common\components\script\behaviors\charging\LogMysqlDBChargingBehavior'
                    ],
                    'logFile'=>[
                        'class'=>'common\components\script\behaviors\charging\LogFileChargingBehavior'
                    ],
                    'logMongoDB'=>[
                        'class'=>'common\components\script\behaviors\charging\LogMongoDBChargingBehavior'
                    ],
                ]
            ],
        ],
        'smsSenders'=>[
            'freeSMS'=>[
                'class'=>'vega\telco\vinaphone\sms\SMSSender',
                'behaviors'=>[
                    'logMysqlDB'=>[
                        'class'=>'common\components\script\behaviors\sms\LogMysqlDBSMSBehavior'
                    ],
                    'logFile'=>[
                        'class'=>'common\components\script\behaviors\sms\LogFileSMSBehavior'
                    ],
                    'logMongoDB'=>[
                        'class'=>'common\components\script\behaviors\sms\LogMongoDBSMSBehavior'
                    ],
                ],
                'baseUrl'=>'http://10.1.10.67:8080/api/soap',
                'username'=>'vclip',
                'password'=>'vclip123',
                'mSISDNSender'=>9234,
                'serviceNumber'=>9234,
                'charge'=>0,
                'messageType'=>0,
                'sMSC'=>9234,
            ],
            'testSMS'=>[
                'class'=>'common\components\test\SMSSender',
                'behaviors'=>[
                    'logMysqlDB'=>[
                        'class'=>'common\components\script\behaviors\sms\LogMysqlDBSMSBehavior'
                    ],
                    'logFile'=>[
                        'class'=>'common\components\script\behaviors\sms\LogFileSMSBehavior'
                    ],
                    'logMongoDB'=>[
                        'class'=>'common\components\script\behaviors\sms\LogMongoDBSMSBehavior'
                    ],
                ],
                'baseUrl'=>'http://210.211.101.16:6090/cp/sendBulkSms',
                'username'=>'mkid',
                'password'=>'mkid@123312',
                'appID'=>'58',
                'key'=>'123',
                'mSISDNSender'=>7062,
                'serviceNumber'=>7062,
                'messageType'=>0,
            ],
        ],
        'urlGenerators'=>[
            'confirmRegistration'=>[
                'class'=>'vega\telco\vinaphone\helper\RedirectUrlGenerator',
                'baseUrl'=>'http://dk1.vinaphone.com.vn/reg.jsp',
                'cPID'=>'VEGA',
                'service'=>'VCLIP',
                'channel'=>1,
                'securePass'=>'vega@4XXs@',
            ],
            'confirmCancellation'=>[
                'class'=>'vega\telco\vinaphone\helper\RedirectUrlGenerator',
                'baseUrl'=>'http://dk1.vinaphone.com.vn/unreg.jsp',
                'cPID'=>'VEGA',
                'service'=>'VCLIP',
                'channel'=>1,
                'securePass'=>'vega@4XXs@',
            ],
            'confirmRegistrationTest'=>[
                'class'=>'vega\telco\vinaphone\helper\RedirectUrlGenerator',
                'baseUrl'=>'http://dangky.mobifone.com.vn/wap/html/sp/confirm_html5.jsp',
                'cPID'=>'VEGA',
                'service'=>'VCLIP',
                'channel'=>1,
                'securePass'=>'vega@4XXs@',
            ],
        ],
    ],
    'scriptManager'=>[
        'class'=>'common\components\ScriptManager',
        'scripts'=>[
            'default'=>[
                'class'=>'common\components\script\Vinaphone',
            ],
            'live'=>[
                'class'=>'common\components\script\VinaphoneLive',
            ],
            'filmContent'=>[
                'class'=>'common\components\script\VinaphoneFilmContent',
            ],
            'clipContent'=>[
                'class'=>'common\components\script\VinaphoneClipContent',
            ],
        ]
    ],
];
